version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-frontend:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-test]
      - run:
          name: Run Frontend Tests
          command: |
              cd frontend
              npm install
              npm run test
                
  test-backend:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      steps:
      - checkout
      - restore_cache:
          keys: [backend-test]
      - run:
          name: Run Backend Tests
          command: |
              cd backend
              npm install
              npm run test

workflows:
  TestWorkflow:
    jobs:
      - build-frontend:
            filters:
              branches:
                only: master
      - build-backend:
            filters:
              branches:
                only: master
      - test-frontend:
            requires: [build-frontend]
            filters:
              branches:
                only: master
      - test-backend:
            requires: [build-backend]
            filters:
              branches:
                only: master